### ISSUE TITLE
Page de résultat

### ISSUE THREAD

**Issue by tlafay** [weishaaan/05_juillet_printWebPageHTML#3]
1 - Changer le texte du bouton "Click me" en "Retour"
2 - Ajouter un message pour l'utilisateur, dans la page de résultat.

![image](https://cloud.githubusercontent.com/assets/19267387/17778350/055bfe8a-6564-11e6-95ce-88d735214d7c.png)

**Comment by weishaaan** [comment]
Bonjour, 
pour ce issue, on doit obtenir les data de web service ou de page HTML, et partager les data dans 2 web pages?
je pense obtenir les data de web service est meilleur.
Comment vous pensez?
http://stackoverflow.com/questions/16264253/sharing-a-variable-between-multiple-html-pages
<img width="858" alt="c623688f-4ce5-4b02-94b4-d5a356b9a00f" src="https://cloud.githubusercontent.com/assets/15628229/17810563/30c3a1ee-661e-11e6-9bfa-a5d6ddf8413d.png">
<img width="739" alt="3cc098c2-0815-412b-9459-5cd27eacc1df" src="https://cloud.githubusercontent.com/assets/15628229/17810564/30e05cf8-661e-11e6-8c9d-a8c49f4e6f41.png">

**Comment by weishaaan** [comment]
parce que dans index.html, on peut obtenir tous les data de $POST par Ajax, mais si on peut réserver les data dans local storage?

**Comment by tlafay** [comment]
Oui. La page doit être générée dans la foulée du traitement d'impression par le web service.

**Comment by tlafay** [comment]
Ne pas stocker en local storage: je crains que l'utilisateur n'autorise pas le stockage en local ou que sur un vieux navigateur le mécanisme ne fonctionne pas.

Il est préférable de passer par un message de retour généré directement par le web service.
