### ISSUE TITLE
Modifier le fichier de configuration des paths et ajouter une fonctionnalité de logs

### ISSUE THREAD

**Issue by tlafay** [weishaaan/05_juillet_printWebPageHTML#5]
1 - renommer le fichier de configuration des paths XML pour pouvoir ajouter d'autres paths (actuellement, on ne définit que le path des fichiers de modèles d'étiquettes). Il faudra adapter la structure du fichier XML/ A essayer: 

![image](https://cloud.githubusercontent.com/assets/19267387/17778658/19b32718-6565-11e6-9c6e-622c5708cea3.png)

2 - ajouter le path des logs dans le fichier de configuration 

```
> <configuration>
> <path>
>     <name>labelmodels</name>
>     <absolutepath>....\Labelmodels</path>
> </path>
> <path>
>     <name>logs</name>
>     <absolutepath>....\Logs</path>
> </path>
> </configuration>
```

3 - ajouter un Logger à GenericRessource pour logger chaque impression d'étiquette
Les logs doivent tracer la date et l'heure + le type d'étiquette + toutes les valeurs modifiées par l'utilisateur + l'imprimante utilisée.

**Comment by weishaaan** [comment]
done.
