### ISSUE TITLE
OF serach Crietia functionality

### ISSUE THREAD

**Issue by tlafay** [weishaaan/05_juillet_printWebPageHTML#7]
Ajouter une fonctionnalité de recherche des OF.
1.  ajouter un panel bootstrap: recherche des OF;
2. dans le panel, ajouter les  input fields suivants:
   ref -> référence;
   sref ->sous référence;
   date1 -> date début période;
   date2 -> date fin période;
   search_buton -> un bouton submit avec le texte "Rechercher".

![image](https://cloud.githubusercontent.com/assets/19267387/17809034/0cc29c1e-6614-11e6-88d5-824d55db2603.png)
1. modifier le web service: ajouter les critères de recherche à getOfList
   ![image](https://cloud.githubusercontent.com/assets/19267387/17809839/88edd9d4-6619-11e6-92a1-386534e1eb2a.png)
2. ajouter les données suivantes pour constituer la liste:
   @GET
   @Path("getOfList")
   @Produces(MediaType.APPLICATION_JSON)
   public List<Of> getOfList(ref, sousref, date1, date2) {
   
   ```
   ArrayList<Of> list = new ArrayList<Of>();
   
   Of ofclass1 = new Of();
   ofclass1.setOfNum(980319);
   ofclass1.setReference(11226200);
   ofclass1.setSreference("0");
   ofclass1.setArtDesignation("LLA3");
   ofclass1.setNbArtPerContainer("20000");
   
   list.add(ofclass1);
   
   Of ofclass2 = new Of();
   ofclass2.setOfNum(980321);
   ofclass2.setReference(11226200);
   ofclass2.setSreference("0");
   ofclass2.setArtDesignation("LLA3");
   ofclass2.setNbArtPerContainer("20000");
   
   list.add(ofclass2);
   
   Of ofclass3 = new Of();
   ofclass3.setOfNum(980322);
   ofclass3.setReference(11178303);
   ofclass3.setSreference("12 M");
   ofclass3.setArtDesignation("BAGUE ANTI BRUIT 9435530 M GRI");
   ofclass3.setNbArtPerContainer("5000");
   list.add(ofclass3);
   
   Of ofclass4 = new Of();
   ofclass4.setOfNum(980323);
   ofclass4.setReference(11216400);
   ofclass4.setSreference("A");
   ofclass4.setArtDesignation("ARMATURE EXT 3279-02 723842");
   ofclass4.setNbArtPerContainer("400");
   list.add(ofclass4);
   
   Of ofclass5 = new Of();
   ofclass5.setOfNum(980324);
   ofclass5.setReference(11219000);
   ofclass5.setSreference("M");
   ofclass5.setArtDesignation("CAPSULE DE ROULEMENT");
   ofclass5.setNbArtPerContainer("600");
   list.add(ofclass5);
   
   Of ofclass6 = new Of();
   ofclass6.setOfNum(980325);
   ofclass6.setReference(11220800);
   ofclass6.setSreference("F");
   ofclass6.setArtDesignation("CONNECTEUR TG 8-12 BORNE A GAU");
   ofclass6.setNbArtPerContainer("30");
   list.add(ofclass6);
   
   Of ofclass7 = new Of();
   ofclass7.setOfNum(980323);
   ofclass7.setReference(11216400);
   ofclass7.setSreference("A");
   ofclass7.setArtDesignation("ARMATURE EXT 3279-02 723842");
   ofclass7.setNbArtPerContainer("400");
   list.add(ofclass7);
   
   Of ofclass8 = new Of();
   ofclass8.setOfNum(980325);
   ofclass8.setReference(11220800);
   ofclass8.setSreference("F");
   ofclass8.setArtDesignation("CONNECTEUR TG 8-12 BORNE A GAU");
   ofclass8.setNbArtPerContainer("30");
   list.add(ofclass8);
   
   Of ofclass9 = new Of();
   ofclass9.setOfNum(980326);
   ofclass9.setReference(11220801);
   ofclass9.setSreference("J");
   ofclass9.setArtDesignation("CONNECTEUR TG 8-12 BORNE A DRO");
   ofclass9.setNbArtPerContainer("30");
   list.add(ofclass9);
   
   Of ofclass10 = new Of();
   ofclass10.setOfNum(980327);
   ofclass10.setReference(11238100);
   ofclass10.setSreference("C");
   ofclass10.setArtDesignation("CANON ISOLANT XG");
   ofclass10.setNbArtPerContainer("5000");
   list.add(ofclass10);
   
   Of ofclass11 = new Of();
   ofclass11.setOfNum(980328);
   ofclass11.setReference(11238300);
   ofclass11.setSreference("A01");
   ofclass11.setArtDesignation("ENJOLIVEUR CLE MVDV");
   ofclass11.setNbArtPerContainer("1000");
   list.add(ofclass11);   
   
   Of ofclass12 = new Of();
   ofclass12.setOfNum(980329);
   ofclass12.setReference(11238500);
   ofclass12.setSreference("A01");
   ofclass12.setArtDesignation("SOFT CLE MVDV");
   ofclass12.setNbArtPerContainer("161");
   list.add(ofclass12);      
   
   
   Of ofclass13 = new Of();
   ofclass13.setOfNum(980330);
   ofclass13.setReference(11239000);
   ofclass13.setSreference("A");
   ofclass13.setArtDesignation("OUTER SLEEVE 2023-02PSA065-02E");
   ofclass13.setNbArtPerContainer("800");
   list.add(ofclass13);      
   
   Of ofclass14 = new Of();
   ofclass14.setOfNum(980331);
   ofclass14.setReference(11239300);
   ofclass14.setSreference("N2");
   ofclass14.setArtDesignation("PROTECTEUR DE COLLECTEUR");
   ofclass14.setNbArtPerContainer("900");
   list.add(ofclass14);  
   
   Of ofclass15 = new Of();
   ofclass15.setOfNum(980332);
   ofclass15.setReference(11239800);
   ofclass15.setSreference("B1");
   ofclass15.setArtDesignation("CAPOT TG 8/12");
   ofclass15.setNbArtPerContainer("80");
   list.add(ofclass15);  
   
   
   return list;
   ```
   
   }

**Comment by tlafay** [comment]
La dynamique de l'écran devient la suivante:
1. l'utilisateur affiche la page avec un liste d'Of vide : il ne peut rien renvoyer au webservice
2. l'utilisateur entre ses critères de recherche dans le nouveau panel: reference, sous-reference, date1, date2
3. lorsqu'il clique sur le bouton "rechercher", on POST ces critères au webservice (méthode getOfList()
4. le web service retourne une liste d'Of qui correspond aux critères de recherche
5. la page web rafraîchit la liste des Of

A partir de là, on se retrouve dans la situation d'avant: l'utilisateur sélectionne son Of, son imprimante et son modèle d'étiquette ... puis il envoie le POST au webservice pour impression des étiquettes.

Pour le point 3, tu peux peut-être effectuer l'appel en ajax et rafraîchir la liste avec l'objet Json renvoyé par le webservice.

**Comment by weishaaan** [comment]
(1) Je crée une nouvelle classe OF pour réserver (ref, sousref, date1, date2) ces 4 critère? 
(2) Of classe :  
   long ofNum;
   long reference;
   String sreference;
   String artDesignation;
   String nbArtPerContainer;
   int qteOfEntete;
   Date datePlainfDebut;

Comment on filtre ces 4 critères (ref, sousref, date1, date2) ?
  tout à bord, ref---> souref ----> date 1 ---> et puis date2 ??

Merci.

**Comment by tlafay** [comment]
On ne crée pas de nouvelle classe .... on ajoute les propriété à la classe actuelle.

Pas besoin de filtrer pour le moment. Je le coderai plus tard.

**Comment by weishaaan** [comment]
Bonjour monsieur, je vous attends pour le m-a-j de code ^^ merci

**Comment by tlafay** [comment]
Dymanique de l'écran:
1 - saisie par l'utilisateur d'une référence
2 - click sur search
3 - mise à jour des données sur la liste des Of

![image](https://cloud.githubusercontent.com/assets/19267387/17850179/4de5a782-685c-11e6-9347-10e342a030cc.png)
